#!/bin/bash
# Run the buildnmal for mizuRoute, assing it's under a CTSM or CESM checkout
cd ../../../../cime >& /dev/null
if [ $? != 0 ]; then
   echo "cime directory does not exist where expected"
   exit -1
fi
export CIMEROOT=`pwd`
echo "CIMEROOT = $CIMEROOT"
    
cd -
cp ../user_nl_* .
mkdir CaseDocs
echo "Run the help option"
../buildnml --help > /dev/null
if [ $? != 0 ] ; then
   echo "test FAIL"
   exit -1
fi
echo "Try a simple test"
../buildnml `pwd` --verbose
if [ $? != 0 ] ; then
   echo "test FAIL"
   exit -1
else
   echo "Cat the results...."
   cat Buildconf/mizurouteconf/mizuRoute*
   echo "input_data_list..."
   cat Buildconf/mizuroute.input_data_list
fi
rm -rf user_* run/* Buildconf/mizurouteconf/* Buildconf/* CaseDocs
echo "Successfully ran test"
