#!/bin/bash
cd ../../cime >& /dev/null
if [ $? != 0 ]; then
   cd ../../../../cime
fi
export CIMEROOT=`pwd`
    
cd -
cp ../user_* .
mkdir CaseDocs
echo "Run the help option"
../buildnml --help > /dev/null
if [ $? != 0 ] ; then
   echo "test FAIL"
   exit -1
fi
echo "Try a simple test"
../buildnml `pwd` --verbose
if [ $? != 0 ] ; then
   echo "test FAIL"
   exit -1
else
   cat Buildconf/mizurouteconf/mizuRoute*
fi
#rm -rf user_* run/* Buildconf/mizurouteconf/* Buildconf/* CaseDocs
echo "Successfully ran test"
